from __future__ import annotations
import logging
from dataclasses import dataclass

from shasta.ast_node import (
    AndNode,
    AstNode,
    CaseNode,
    CommandNode,
    DefunNode,
    ForNode,
    IfNode,
    NotNode,
    OrNode,
    PipeNode,
    RedirectionNode,
    SemiNode,
    SubshellNode,
    WhileNode,
)
# from shseer import reporter,error_report
from typing import Optional

class Config:
    __conf = {
    "CONCRETE_CWD": True,
    "CWD_PATH" : "/",
    "ERROR_ON_FAILURE": True,
    "FULL_REPR": False,
    "TIME_LIMIT": 5,
    "SMTFILE": False,
    "SMTSTATS": False,
    "LOCALVARFILE" : "local_vars.txt",
    "WHILE_UNROLL_LIMIT" : 2,
    "MAX_UNROLL_LIMIT" : 10,
    "SMTTIMEOUT" : 5_500, #The unit here is milliseconds,
    "ASSUME_SIDE_EFFECTS" : False,
    "DEBUG":True,
    "SCCHECK" : False,
    }
    __setters = ["DEBUG"]

    @staticmethod
    def get(name):
        return Config.__conf[name]

    @staticmethod
    def set(name, value):
        if name in Config.__setters:
            Config.__conf[name] = value
        else:
            raise ValueError(f"Only {Config.__setters} can be modified")
        
class NodeSymMaps:
    _maps : list[NodeMap] = []
    @staticmethod
    def getmap():
        x = NodeMap()
        NodeSymMaps._maps.append(x)
        return x
    
    @staticmethod
    def addmap(x:NodeMap):
        NodeSymMaps._maps.append(x)

    @staticmethod
    def getallmaps():
        return NodeSymMaps._maps

@dataclass(frozen=True)
class RawNode:
    ast_node: AstNode
    rawtext: str
    line_before: int
    line_after: int  # relevant for mysterious shell reasons


@dataclass()
class ConditionalVisit:
    true_followed : bool = False
    false_followed : bool = False

    def combine(self,other:ConditionalVisit):
        self.true_followed = self.true_followed or other.true_followed
        self.false_followed = self.false_followed or other.false_followed
@dataclass()
class ASTNodeVisit:
    raw_text : str
    conditional : Optional[ConditionalVisit] = None  #if cond ,while cond, first arg of and/or , not arg
    visited : bool = False 
    constant : bool = True
    
    def set_visited(self):
        self.visited = True
    
    def set_not_constant(self):
        self.constant = False
        
NodeMap = dict[int,ASTNodeVisit]


# class AstNodeWithContent:
#     def __init__(self, node: AstNode, content: str = None):
#         self.node = node
#         if content:
#             self.content = content
#         else:
#             self.get_content()
    
#     def get_content(self):
#         self.content = self.node.pretty()

def traverse_node(nd : AstNode, pipelines_nodes : list[AstNode]):
    match nd:
        case CommandNode():
            return
        case DefunNode():
            return
        case IfNode():
            traverse_node(nd.cond, pipelines_nodes)
            traverse_node(nd.then_b, pipelines_nodes)
            traverse_node(nd.else_b, pipelines_nodes)
        case AndNode():
            traverse_node(nd.left_operand, pipelines_nodes)
            traverse_node(nd.right_operand, pipelines_nodes)
        case OrNode():
            traverse_node(nd.left_operand, pipelines_nodes)
            traverse_node(nd.right_operand, pipelines_nodes)
        case NotNode():
            traverse_node(nd.body, pipelines_nodes)
        case ForNode():
            traverse_node(nd.body, pipelines_nodes)
        case WhileNode():
            traverse_node(nd.test, pipelines_nodes)
            traverse_node(nd.body, pipelines_nodes)
        case CaseNode():
            for case in nd.cases:
                traverse_node(case["cbody"], pipelines_nodes)
        case PipeNode():
            pipelines_nodes.append(nd)
        case SemiNode():
            traverse_node(nd.left_operand, pipelines_nodes)
            traverse_node(nd.right_operand, pipelines_nodes)
        case SubshellNode():
            traverse_node(nd.body, pipelines_nodes)
        case RedirectionNode():
            return
        case _:
            logging.debug(f"Node not handled: {nd}")
    

def traverse_raw_nodes(ls : list[RawNode]) -> list[AstNode]:
    pipeline_nodes = []
    for nd in ls:
        traverse_node(nd.ast_node, pipeline_nodes)
    return pipeline_nodes

def combine_maps(ls_m : list[NodeMap]) -> NodeMap:
    """
    Combine the dictionaries generated by each symbolic path such that:
    raw_text pick any (shouldn't matter)
    conditional Take or
    visited Take Or of all
    constant Take And of all
    """
    if not ls_m:
        return {}
    result = {}
    all_keys = set().union(*ls_m)
    
    for key in all_keys:
        nodes = [m[key] for m in ls_m if key in m]
        
        # Pick any raw_text (shouldn't matter)
        raw_text = nodes[0].raw_text

        # Assert that all conditionals are the same, then pick any
        cmb_cond = ConditionalVisit()
        for cnd in [node.conditional for node in nodes]:
            if cmb_cond is None or cnd is None:
                cmb_cond = cnd 
            else:
                cmb_cond.combine(cnd)
        conditional = cmb_cond

        # Take Or of all visited
        visited = any(node.visited for node in nodes)

        # Take And of all constant
        constant = all(node.constant for node in nodes)

        result[key] = ASTNodeVisit(
            raw_text=raw_text,
            conditional=conditional,
            visited=visited,
            constant=constant
        )

    return result
    