# Evaluation settings
enable_timeout: false
timeout_seconds: 10
enable_user_annotation: true
num_workers: 1

# Heuristic rules
enable_rule_no_empty_output: true
enable_rule_no_ignored_input: true
enable_rule_no_meaningless_command: true
enable_rule_no_sort_non_numeric_with_numeric_input: true

# File paths
parsing_error_log_path: evaluation_results/parsing_errors.log

# External tool paths
shellcheck_command: shellcheck
ltsh_command: ltsh
ltsh_typedb_path: ltsh_config/typedb

# Output paths with annotations
output_results_path_with_annotation: evaluation_results/with_annotations/evaluation_results.json
output_summary_path_with_annotation: evaluation_results/with_annotations/summary.csv

# Output paths without annotations
output_results_path_raw: evaluation_results/raw/evaluation_results.json
output_summary_path_raw: evaluation_results/raw/summary.csv

# Pipeline directories
valid_dirs:
  - ./evaluation_pipelines/valid
  - ./full_benchmark/intercode/pipelines
  - ./full_benchmark/github_repos_commits/collected/post_commit
  - ./full_benchmark/pash_benchmark/benchmarks
invalid_dirs:
  - ./evaluation_pipelines/invalid
  - ./full_benchmark/llm_injection/pipelines
  - ./full_benchmark/stackoverflow/buggy
  - ./full_benchmark/github_repos_commits/collected/pre_commit
  - ./evaluation_pipelines/Bad label
  - ./full_benchmark/pash_benchmark/Bad label
  - ./full_benchmark/intercode/Bad label

not_check_all_dirs:
  # - ./full_benchmark/github_repos_commits/output/post_commit
  # - ./full_benchmark/github_repos_commits/output/pre_commit
  - ./full_benchmark/stackoverflow/buggy
  # - ./full_benchmark/stackoverflow/correct
  - ./full_benchmark/github_repos_commits/collected/pre_commit
  - ./full_benchmark/github_repos_commits/collected/post_commit

"benchmark names": {
    "evaluation_pipelines/.*ladder.*": "Ladder",
    "evaluation_pipelines/.*/[0-9_]*.sh": "Handwritten",
    "full_benchmark/intercode/.*": "Intercode",
    "full_benchmark/llm_injection/.*": "LLM",
    "full_benchmark/pash_benchmark/.*": "PaSh",
    "full_benchmark/github_repos_commits/.*": "GitHub",
    "full_benchmark/stackoverflow/.*": "StackOverflow",
    "full_benchmark/koala/.*": "Koala"
}

# Logging
log_level: INFO

# Feature flags
enable_FST: true
enable_concretization: true
